### PR TITLE
Pins to params

### PR DESCRIPTION
**Pull request by Lavaerius**
putting pin layout in paramsrename file, meant to be changed to params.h

various interrupt related things were commented out in this, that I intend on removing in the next pr

### CODE REVIEW

**Comment by quadnegative** [comment]
This is showing a deletion of the platfomio.ini

**Comment by Lavaerius** [comment]
yes, it's a removal of the ini from the repo, and it not being tracked in .gitgnore

it is in the same state as params.h

**Comment by quadnegative** [comment]
But we need the platformio file. That is one of the major upgrades.
googling shows this is the approach 
https://docs.platformio.org/en/latest/projectconf/sections/platformio/options/generic/extra_configs.html
https://github.com/platformio/platformio-core/issues/4036#issuecomment-903236802

**Comment by Lavaerius** [comment]
then we can make it a template file like params.h

it shouldn't

**Comment by Lavaerius** [comment]
just nevermind then

**Pull request closed without merging**
